"""поля для сброса пароля

Revision ID: 2359242af050
Revises: 43461d94e886
Create Date: 2026-06-02 11:55:41.381150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2359242af050'
down_revision: Union[str, Sequence[str], None] = '43461d94e886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('password_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_token_expires_at')
        batch_op.drop_column('password_token')

    # ### end Alembic commands ###
