"""добавлени ячейки model в таблицу с ответами

Revision ID: cbb4f79b5320
Revises: 
Create Date: 2026-05-10 18:14:30.648391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb4f79b5320'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_responses', sa.Column('model', sa.String(), nullable=True))
    op.add_column('ai_responses', sa.Column('prompt', sa.String(), nullable=True))
    op.drop_column('ai_responses', 'request')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_responses', sa.Column('request', sa.VARCHAR(), nullable=True))
    op.drop_column('ai_responses', 'prompt')
    op.drop_column('ai_responses', 'model')
    # ### end Alembic commands ###
